ad

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -27,8 +27,18 @@ jobs:
       run: |
         python -m venv venv
         source venv/bin/activate
-        pip install -r requirements.txt
-        pip install pyinstaller
+        pip install -r requirements.txt 2>&1 | tee $GITHUB_WORKSPACE/pip_output.log
+        if [ $? -ne 0 ]; then
+          echo "Failed to install requirements. See error below:"
+          cat $GITHUB_WORKSPACE/pip_output.log
+          exit 1
+        fi
+        pip install pyinstaller 2>&1 | tee $GITHUB_WORKSPACE/pip_output_pyinstaller.log
+        if [ $? -ne 0 ]; then
+          echo "Failed to install pyinstaller. See error below:"
+          cat $GITHUB_WORKSPACE/pip_output_pyinstaller.log
+          exit 1
+        fi
         echo "VIRTUAL_ENV=$(pwd)/venv" >> $GITHUB_ENV
         echo "PATH=$(pwd)/venv/bin:$PATH" >> $GITHUB_ENV
 
@@ -41,22 +51,20 @@ jobs:
         Write-Host "Created virtual environment."
         .\venv\Scripts\Activate.ps1
         Write-Host "Activated virtual environment."
-        pip install -r requirements.txt 2>&1 | Tee-Object -FilePath "$(pwd)\pip_output.log"
-        if ($LASTEXITCODE -eq 0) {
-          Write-Host "Installed requirements successfully."
-        } else {
+        pip install -r requirements.txt 2>&1 | Tee-Object -FilePath "$env:GITHUB_WORKSPACE\pip_output.log"
+        if ($LASTEXITCODE -ne 0) {
           Write-Host "Failed to install requirements. See error below:"
-          Get-Content "$(pwd)\pip_output.log"
+          Get-Content "$env:GITHUB_WORKSPACE\pip_output.log"
           exit 1
         }
-        pip install pyinstaller 2>&1 | Tee-Object -FilePath "$(pwd)\pip_output_pyinstaller.log"
-        if ($LASTEXITCODE -eq 0) {
-          Write-Host "Installed pyinstaller successfully."
-        } else {
+        Write-Host "Installed requirements successfully."
+        pip install pyinstaller 2>&1 | Tee-Object -FilePath "$env:GITHUB_WORKSPACE\pip_output_pyinstaller.log"
+        if ($LASTEXITCODE -ne 0) {
           Write-Host "Failed to install pyinstaller. See error below:"
-          Get-Content "$(pwd)\pip_output_pyinstaller.log"
+          Get-Content "$env:GITHUB_WORKSPACE\pip_output_pyinstaller.log"
           exit 1
         }
+        Write-Host "Installed pyinstaller successfully."
         echo "VIRTUAL_ENV=$(pwd)\\venv" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
         Write-Host "Updated VIRTUAL_ENV."
         echo "PATH=$(pwd)\\venv\\Scripts;$env:PATH" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
@@ -70,8 +78,8 @@ jobs:
       with:
         name: log-files
         path: |
-          $(pwd)\pip_output.log
-          $(pwd)\pip_output_pyinstaller.log
+          ${{ github.workspace }}\pip_output.log
+          ${{ github.workspace }}\pip_output_pyinstaller.log
 
     - name: Build executable (Linux)
       if: runner.os != 'Windows'
